### ISSUE TITLE
For JSON response matcher, spaces in Content-Type header don't matter

### ISSUE THREAD

**Issue by koterpillar** [hspec/hspec-wai#37]
According to [RFC 2045](https://www.ietf.org/rfc/rfc2045.txt), spaces aren't required in `Content-Type: application/json; charset=utf-8` - there can be any number of them after the semicolon, including zero. This should be taken into account for the JSON response matcher, as the following headers are valid:

`Content-Type: application/json;charset=utf-8` (note that `http-media` produces this)

`Content-Type: application/json;    charset=utf-8`

**Comment by sol** [comment]
+1

**Comment by koterpillar** [comment]
While this is still valid, see #39 for the correct behavior.
