### ISSUE TITLE
Support matching json body with non-standard content type

### ISSUE THREAD

**Issue by begriffs** [hspec/hspec-wai#44]
My app uses a vendored mime type (`application/vnd.foo.bar+json`) in certain responses, so `` `shouldRespondWith` [json| ... |]`` fails. I'd rather not fall back to string matches though because then the order of the keys in my json objects matter in the tests. Exposing `equalsJSON` would let me create my own matcher like:

```haskell
jsonMatch j =
  ResponseMatcher {
    matchBody    = equalsJSON j
  , matchStatus  = 200
  , matchHeaders = [
      "Content-Type" <:>
      "application/vnd.foo.bar+json; charset=utf-8"
    ]
  }
```

But maybe you know a more elegant way.

**Comment by sol** [comment]
```haskell
get "foo" `shouldRespondWith` [json| ... |] {matchHeaders = ["Content-Type" <:> "application/vnd.foo.bar+json; charset=utf-8"]}
```
How about this?

**Comment by sol** [comment]
@begriffs I'm closing this.  If you want any code changes please send a PR.

**Comment by begriffs** [comment]
Sorry I didn't respond earlier. I ended up getting it working along the lines of what you said.
