### ISSUE TITLE
Json matcher doesn't accept correct header

### ISSUE THREAD

**Issue by Philonous** [hspec/hspec-wai#46]
I'm trying to test a REST api written in servant. To that end I have a test like this:

```haskell
get "/users" `shouldRespondWith` [json|[{"name":"bob"}]|]
```

That test fails with

```
  1) GET /users responds with [User]
       missing header:
         Content-Type: application/json
       the actual headers were:
         Content-Type: application/json;charset=utf-8
```

The actual header is compatible with the required one, so this shouldn't fail.

**Comment by sol** [comment]
@Philonous As I understand it `application/json; charset=utf-8` is non-standard.  See also https://github.com/hspec/hspec-wai/pull/40 and [elsewhere on the Internet](https://github.com/request/request/issues/383).

**Comment by sol** [comment]
@Philonous if you want to test your current behavior, you can do this with:

```haskell
get "/users" `shouldRespondWith` [json|[{"name":"bob"}]|] {matchHeaders = ["Content-Type" <:> "application/json; charset=utf-8"]}
```

**Comment by sol** [comment]
@jkarni any opinion on this.  Have you had a discussion on what the right thing for `servant` is before?

**Comment by Philonous** [comment]
Servant seems to implement it on purpose to appease other clients (see https://github.com/haskell-servant/servant/issues/849). 

Also, the [JSON rfc](https://tools.ietf.org/html/rfc7159) remarks that although it isn't defined, it should be ignored by compliant recipients:

> Note: No "charset" parameter is defined for this registration.
> Adding one really has no effect on compliant recipients.

So I think this should be fixed here and have implemented a patch: https://github.com/hspec/hspec-wai/pull/47

**Comment by sol** [comment]
I added a lengthy source code comment in https://github.com/hspec/hspec-wai/commit/791dcbb48dff41735b53758d988b8754ad7dc49b that elaborates my view on this matter.

**Comment by sol** [comment]
Fixed.

**Comment by Philonous** [comment]
Thanks :)
