### ISSUE TITLE
Analyse the response body (instead of expecting an exact value)

### ISSUE THREAD

**Issue by JivanRoquet** [hspec/hspec-wai#62]
Is there a way to get the response body and perform tests on it?

Let's say I get a response body like this:

```json
{
    "results": [42, 12, 66, 73, 59]
}
```

and all I care about is that there are `5` items in `results` and they are all `Int`. I don't care about each individual value.

I could not find any obvious way to achieve this by reading the code.

**Comment by JivanRoquet** [comment]
The only alternative I can think of at the moment is throwing `hspec-wai` altogether and run the API for real during the tests, then query the endpoints for real, get the response body, and analyse it. Any alternative using `hspec-wai` would be tremendously useful.

**Comment by sol** [comment]
`get` returns an `SResponse`.  As a fallback, you can just do with it whatever suits you, e.g. (untested):

```haskell
r <- get "/foo"
let body = simpleBody r
case decode body of
  Right (Object o) | Just (Array xs) <- HM.lookup "results" o -> V.length xs `shouldBe` 5
  _ -> expectationFailure $ unexpected response <> show body
```

**Comment by sol** [comment]
You may still be better of to define some data type for your expected response + a `FromJSON` instance for it and `decode` that.  Working with `Value` is notoriously inconvenient.

**Comment by JivanRoquet** [comment]
Sounds good. Thanks for the guidance.
